name: ios-ota-download

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: macos-12
    name: "download"
    steps:
      - name: Install IPSW
        run: |
          set -eou pipefail
          brew update
          brew install blacktop/tap/ipsw
      - name: Install symsorter
        run: |
          set -eou pipefail
          curl -L https://github.com/getsentry/symbolicator/releases/download/0.5.1/symsorter-Darwin-universal > symsorter
          chmod +x symsorter
      - name: OTA download (this is useless WIP right now)
        run: |
          set -eou pipefail
          ipsw device-list
          ipsw download ota --info --platform ios --info-type iOS
          ipsw download ota --platform ios --version 16.0.3 --device iPhone14,2